# Generated by Django 5.1.3 on 2024-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='recording_path',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
